# Assignment 5: For Loops, Range, and Code Blocks

#### Task 1: Print all even numbers from 1 to 10.

In [4]:
for i in range(2,11,2):
  print(i)

2
4
6
8
10

#### Task 2: Calculate the sum of numbers from 1 to 100.

In [3]:
total = sum(range(1,101))
print("The sum of numbers from 1 to 100 is: ",total)

The sum of numbers from 1 to 100 is:  5050

#### Task 3: Loop through a fixed list of fruits and print each fruit.

In [1]:
fruits = ["apple","banana","cherry","date"]
for fruit in fruits:
  print(fruit)

apple
banana
cherry
date

###  Sample Outputs


```
2
4
6
8
10
The sum of numbers from 1 to 100 is: 5050
apple
banana
cherry
date
```